apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gwrp.fullname" . }}
  labels:
    {{- include "gwrp.labels" . | nindent 4 }}
data:
  githubSecretKey: {{ .Values.github.secretKey | b64enc }}
